"""reserva ativa unica por usuario

Revision ID: 804d84890a9e
Revises: e917534ed28d
Create Date: 2026-09-10 21:35:58.110931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '804d84890a9e'
down_revision: Union[str, Sequence[str], None] = 'e917534ed28d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_reservas_usuario_ativa_unica', 'reservas', ['usuario_id'], unique=True, postgresql_where=sa.text("status = 'ATIVA'"), sqlite_where=sa.text("status = 'ATIVA'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reservas_usuario_ativa_unica', table_name='reservas', postgresql_where=sa.text("status = 'ATIVA'"), sqlite_where=sa.text("status = 'ATIVA'"))
    # ### end Alembic commands ###
