"""criacao inicial das tabelas

Revision ID: e917534ed28d
Revises: 
Create Date: 2026-09-10 19:35:48.540370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e917534ed28d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('armarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('DISPONIVEL', 'RESERVADO', 'OCUPADO', 'MANUTENCAO', name='statusarmario'), nullable=False),
    sa.Column('tamanho', sa.Enum('PEQUENO', 'MEDIO', 'GRANDE', name='tamanhoarmario'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_armarios_numero'), 'armarios', ['numero'], unique=True)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('papel', sa.Enum('ASSOCIADO', 'ADMIN', name='papelusuario'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('reservas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('armario_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('status', sa.Enum('ATIVA', 'CONCLUIDA', 'CANCELADA', name='statusreserva'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['armario_id'], ['armarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservas_armario_id'), 'reservas', ['armario_id'], unique=False)
    op.create_index(op.f('ix_reservas_usuario_id'), 'reservas', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reservas_usuario_id'), table_name='reservas')
    op.drop_index(op.f('ix_reservas_armario_id'), table_name='reservas')
    op.drop_table('reservas')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_armarios_numero'), table_name='armarios')
    op.drop_table('armarios')
    # ### end Alembic commands ###
